In [2]:
from db_utils import run_query, execute_ddl

### 1. Retrieve the top 10 departments by total visit volume.

In [3]:
from db_utils import run_query, execute_ddl

create_view_query = """
CREATE OR REPLACE VIEW vw_operational_department_visit_volume AS
SELECT
    department,
    COUNT(*) AS total_visits
FROM visits
GROUP BY department
ORDER BY total_visits DESC
LIMIT 10;
"""

execute_ddl(create_view_query)

# Pull the view's data into a DataFrame to verify
df_dept_volume = run_query("SELECT * FROM vw_operational_department_visit_volume;")
df_dept_volume

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  total_visits
0      General          4228
1           ER          4220
2    Neurology          4165
3  Orthopedics          4164
4   Cardiology          4159
5          ICU          4064

### 2. Identify the top 5 departments with the highest average length of stay.

In [4]:
create_view_query_avg_stay_length = """
CREATE OR REPLACE VIEW vw_operational_department_avg_stay_length AS
SELECT department,
AVG(length_of_stay_hours) AS avg_length_of_stay_hrs
FROM visits
GROUP BY department
ORDER BY avg_length_of_stay_hrs DESC
LIMIT 5;
"""

execute_ddl(create_view_query_avg_stay_length)

# Pull the view's data into a DataFrame to verify
df_dept_avg_stay_length = run_query("SELECT * FROM vw_operational_department_avg_stay_length;")
df_dept_avg_stay_length

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  avg_length_of_stay_hrs
0    Neurology               19.718098
1  Orthopedics               19.662656
2   Cardiology               19.600962
3           ER               19.534967
4      General               19.434905

### 3 Find the percentage of High Risk visits per department.

In [5]:
create_view_query_high_risk_pct = """
CREATE OR REPLACE VIEW vw_operational_department_high_risk_pct AS
SELECT department,
ROUND(SUM(risk_score = "High")/ COUNT(risk_score)* 100,2) as percentage_high_risk_visits
FROM visits
GROUP BY department
ORDER BY percentage_high_risk_visits desc;
"""

execute_ddl(create_view_query_high_risk_pct)

df_high_risk_pct = run_query("SELECT * FROM vw_operational_department_high_risk_pct;")
df_high_risk_pct

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  percentage_high_risk_visits
0          ICU                        20.79
1           ER                        20.66
2    Neurology                        20.31
3  Orthopedics                        20.22
4      General                        19.84
5   Cardiology                        18.99

### 4 Determine the average number of visits per patient by city.

In [6]:
create_view_query_visits_per_patient = """
CREATE OR REPLACE VIEW vw_operational_city_avg_visits_per_patient AS
SELECT city,
ROUND(COUNT(visit_id) / COUNT(DISTINCT visits.patient_id), 2) as avg_visits_per_patient
FROM visits JOIN patients
ON visits.patient_id = patients.patient_id
GROUP BY city
ORDER BY avg_visits_per_patient DESC;
"""

execute_ddl(create_view_query_visits_per_patient)

df_visits_per_patient = run_query("SELECT * FROM vw_operational_city_avg_visits_per_patient;")
df_visits_per_patient

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

        city  avg_visits_per_patient
0       Pune                    5.12
1  Hyderabad                    5.06
2  Bangalore                    5.02
3    Chennai                    5.02
4     Mumbai                    5.02
5      Delhi                    4.95

### 5 Identify doctors handling the highest number of High Risk visits.

In [7]:
create_view_query_doctor_high_risk = """
CREATE OR REPLACE VIEW vw_operational_doctor_high_risk_visits AS
SELECT doctor_id,
SUM(risk_score = "High") as high_risk_visit_count
FROM visits
GROUP BY doctor_id
ORDER BY high_risk_visit_count DESC;
"""

execute_ddl(create_view_query_doctor_high_risk)

df_doctor_high_risk = run_query("SELECT * FROM vw_operational_doctor_high_risk_visits;")
df_doctor_high_risk

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

     doctor_id  high_risk_visit_count
0          174                   71.0
1          198                   69.0
2          169                   68.0
3          177                   67.0
4          105                   65.0
..         ...                    ...
96         124                   38.0
97         175                   38.0
98         148                   37.0
99         128                   37.0
100        137                   34.0

[101 rows x 2 columns]

# FINANCIAL ANALYSIS

### 1 Retrieve the top 10 insurance providers by total billed amount.

In [8]:
create_view_query_insurance_total_billed = """
CREATE OR REPLACE VIEW vw_financial_insurance_provider_total_billed AS
SELECT insurance_provider,
ROUND(SUM(billed_amount),2) as total_billed_amount
FROM visits as t1 JOIN billing as t2 
ON t1.visit_id = t2.visit_id
JOIN patients as t3 
ON t1.patient_id = t3.patient_id
GROUP BY insurance_provider
ORDER BY total_billed_amount DESC
LIMIT 10;
"""

execute_ddl(create_view_query_insurance_total_billed)

df_insurance_total_billed = run_query("SELECT * FROM vw_financial_insurance_provider_total_billed;")
df_insurance_total_billed

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

  insurance_provider  total_billed_amount
0          MediCareX         1.345912e+08
1            CareOne         1.307080e+08
2         HealthPlus         1.301807e+08
3         SecureLife         1.262890e+08

### 2. Identify the top 5 insurance providers with the highest claim rejection rate.

In [9]:
create_view_query_claim_rejection_rate = """
CREATE OR REPLACE VIEW vw_financial_insurance_claim_rejection_rate AS
SELECT insurance_provider,
ROUND(SUM(t2.claim_status = "Rejected") / COUNT(t2.claim_status) * 100, 2) as claim_rejection_rate
FROM visits as t1 JOIN billing as t2 
ON t1.visit_id = t2.visit_id
JOIN patients as t3 
ON t1.patient_id = t3.patient_id
GROUP BY insurance_provider
ORDER BY claim_rejection_rate DESC
LIMIT 5;
"""

execute_ddl(create_view_query_claim_rejection_rate)

df_claim_rejection_rate = run_query("SELECT * FROM vw_financial_insurance_claim_rejection_rate;")
df_claim_rejection_rate

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

  insurance_provider  claim_rejection_rate
0         SecureLife                 15.69
1          MediCareX                 15.25
2         HealthPlus                 14.97
3            CareOne                 14.87

### 3 Find the average payment delay (payment_days) by insurance provider.

In [10]:
create_view_query_payment_delay = """
CREATE OR REPLACE VIEW vw_financial_insurance_payment_delay_claim_status_wise AS
SELECT insurance_provider,
claim_status,
ROUND(AVG(t2.payment_days), 2) as avg_payment_delay
FROM visits as t1 JOIN billing as t2 
ON t1.visit_id = t2.visit_id
JOIN patients as t3 
ON t1.patient_id = t3.patient_id
GROUP BY insurance_provider, claim_status
ORDER BY insurance_provider, claim_status;
"""

execute_ddl(create_view_query_payment_delay)

df_payment_delay = run_query("SELECT * FROM vw_financial_insurance_payment_delay_claim_status_wise;")
df_payment_delay

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

   insurance_provider claim_status  avg_payment_delay
0             CareOne         Paid              12.46
1             CareOne      Pending              14.33
2             CareOne     Rejected              13.14
3          HealthPlus         Paid              12.63
4          HealthPlus      Pending              13.65
5          HealthPlus     Rejected              13.88
6           MediCareX         Paid              12.50
7           MediCareX      Pending              14.14
8           MediCareX     Rejected              13.10
9          SecureLife         Paid              12.52
10         SecureLife      Pending              14.18
11         SecureLife     Rejected              13.52

### 4 Calculate the revenue realization ratio (approved_amount / billed_amount) by department.

In [11]:
create_view_query_revenue_realisation = """
CREATE OR REPLACE VIEW vw_financial_department_revenue_realisation_ratio AS
SELECT department,
ROUND(SUM(approved_amount)/SUM(billed_amount), 2) as revenue_realisation_ratio
FROM visits as t1 JOIN billing as t2
ON t1.visit_id = t2.visit_id 
GROUP BY t1.department
ORDER BY revenue_realisation_ratio DESC;
"""

execute_ddl(create_view_query_revenue_realisation)

df_revenue_realisation = run_query("SELECT * FROM vw_financial_department_revenue_realisation_ratio;")
df_revenue_realisation

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  revenue_realisation_ratio
0          ICU                       0.75
1   Cardiology                       0.74
2           ER                       0.74
3      General                       0.74
4    Neurology                       0.74
5  Orthopedics                       0.74

### 5. Identify visits where billed_amount is high but approved_amount is zero or missing.

In [12]:
create_view_query_high_billed_zero_approved = """
CREATE OR REPLACE VIEW vw_financial_high_billed_zero_approved AS
SELECT 
    t1.visit_id,
    t1.department,
    t2.billed_amount,
    t2.approved_amount,
    t2.claim_status
FROM visits as t1 JOIN billing as t2
ON t1.visit_id = t2.visit_id
WHERE t2.billed_amount > 20000
AND (t2.approved_amount = 0 OR t2.approved_amount IS NULL)
ORDER BY t2.billed_amount DESC;
"""

execute_ddl(create_view_query_high_billed_zero_approved)

df_high_billed_zero_approved = run_query("SELECT * FROM vw_financial_high_billed_zero_approved;")
df_high_billed_zero_approved

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

      visit_id   department  billed_amount  approved_amount claim_status
0         1570      General        78054.8              NaN         Paid
1        18381      General        68213.5              0.0     Rejected
2        15092    Neurology        66410.3              NaN         Paid
3         2638    Neurology        65167.4              NaN         Paid
4         8089           ER        62661.8              NaN         Paid
...        ...          ...            ...              ...          ...
2327     12676  Orthopedics        20015.9              0.0     Rejected
2328      6693    Neurology        20014.7              0.0     Rejected
2329     12582           ER        20009.6              NaN     Rejected
2330      1359  Orthopedics        20009.0              0.0     Rejected
2331      3992  Orthopedics        20008.5              NaN         Paid

[2332 rows x 5 columns]

# Data Quality and Integrity Checks

### 1. Detect visits that do not have a corresponding billing record.

In [13]:
create_view_query_no_billing_record = """
CREATE OR REPLACE VIEW vw_data_quality_visits_no_billing_record AS
SELECT t1.visit_id
FROM visits as t1 LEFT JOIN billing as t2
ON t1.visit_id = t2.visit_id
WHERE t2.bill_id IS NULL;
"""

execute_ddl(create_view_query_no_billing_record)

df_no_billing_record = run_query("SELECT * FROM vw_data_quality_visits_no_billing_record;")
df_no_billing_record

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

Empty DataFrame
Columns: [visit_id]
Index: []

### 2. Detect billing records that do not have a corresponding visit.

In [14]:
create_view_query_no_visit_record = """
CREATE OR REPLACE VIEW vw_data_quality_billing_no_visit_record AS
SELECT t1.bill_id
FROM billing as t1 LEFT JOIN visits as t2
ON t1.visit_id = t2.visit_id
WHERE t2.visit_id IS NULL;
"""

execute_ddl(create_view_query_no_visit_record)

df_no_visit_record = run_query("SELECT * FROM vw_data_quality_billing_no_visit_record;")
df_no_visit_record

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

Empty DataFrame
Columns: [bill_id]
Index: []

### 3. Identify patients with duplicate patient_id values.

In [15]:
create_view_query_duplicate_patients = """
CREATE OR REPLACE VIEW vw_data_quality_duplicate_patient_ids AS
SELECT patient_id,
COUNT(*) as occurrences
FROM patients
GROUP BY patient_id
HAVING COUNT(*) > 1;
"""

execute_ddl(create_view_query_duplicate_patients)

df_duplicate_patients = run_query("SELECT * FROM vw_data_quality_duplicate_patient_ids;")
df_duplicate_patients

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

Empty DataFrame
Columns: [patient_id, occurrences]
Index: []

### 4. Find records with missing or invalid length_of_stay_hours or payment_days.

In [18]:
create_view_query_missing_invalid_fields = """
CREATE OR REPLACE VIEW vw_data_quality_missing_invalid_stay_payment AS
SELECT 
    t1.visit_id,
    t1.length_of_stay_hours,
    t2.payment_days
FROM visits as t1 JOIN billing as t2
ON t1.visit_id = t2.visit_id
WHERE t1.length_of_stay_hours IS NULL
    OR t1.length_of_stay_hours <= 0
    OR t2.payment_days IS NULL
    OR t2.payment_days <= 0;
"""

execute_ddl(create_view_query_missing_invalid_fields)

df_missing_invalid = run_query("SELECT * FROM vw_data_quality_missing_invalid_stay_payment;")
df_missing_invalid

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

     visit_id  length_of_stay_hours payment_days
0           3                 34.36         None
1          22                 15.27         None
2          41                 18.26         None
3          66                  9.59         None
4         109                 21.18         None
..        ...                   ...          ...
785     24842                 10.48         None
786     24851                 27.29         None
787     24896                 18.86         None
788     24944                 26.58         None
789     24988                 13.85         None

[790 rows x 3 columns]

### 5. Identify visits linked to patients with missing insurance provider information.

In [19]:
create_view_query_missing_insurance = """
CREATE OR REPLACE VIEW vw_data_quality_visits_missing_insurance AS
SELECT
    t1.visit_id,
    t1.patient_id,
    t1.visit_date,
    t1.department,
    t2.insurance_provider
FROM visits as t1 JOIN patients as t2
ON t1.patient_id = t2.patient_id
WHERE t2.insurance_provider IS NULL
    OR t2.insurance_provider = '';
"""

execute_ddl(create_view_query_missing_insurance)

df_missing_insurance = run_query("SELECT * FROM vw_data_quality_visits_missing_insurance;")
df_missing_insurance

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

Empty DataFrame
Columns: [visit_id, patient_id, visit_date, department, insurance_provider]
Index: []