In [2]:
from db_utils import run_query, execute_ddl

### 1. Retrieve the top 10 departments by total visit volume.

In [3]:
from db_utils import run_query, execute_ddl

create_view_query = """
CREATE OR REPLACE VIEW vw_operational_department_visit_volume AS
SELECT
    department,
    COUNT(*) AS total_visits
FROM visits
GROUP BY department
ORDER BY total_visits DESC
LIMIT 10;
"""

execute_ddl(create_view_query)

# Pull the view's data into a DataFrame to verify
df_dept_volume = run_query("SELECT * FROM vw_operational_department_visit_volume;")
df_dept_volume

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  total_visits
0      General          4228
1           ER          4220
2    Neurology          4165
3  Orthopedics          4164
4   Cardiology          4159
5          ICU          4064

### 2. Identify the top 5 departments with the highest average length of stay.

In [4]:
create_view_query_avg_stay_length = """
CREATE OR REPLACE VIEW vw_operational_department_avg_stay_length AS
SELECT department,
AVG(length_of_stay_hours) AS avg_length_of_stay_hrs
FROM visits
GROUP BY department
ORDER BY avg_length_of_stay_hrs DESC
LIMIT 5;
"""

execute_ddl(create_view_query_avg_stay_length)

# Pull the view's data into a DataFrame to verify
df_dept_avg_stay_length = run_query("SELECT * FROM vw_operational_department_avg_stay_length;")
df_dept_avg_stay_length

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  avg_length_of_stay_hrs
0    Neurology               19.718098
1  Orthopedics               19.662656
2   Cardiology               19.600962
3           ER               19.534967
4      General               19.434905

### 3 Find the percentage of High Risk visits per department.

In [5]:
create_view_query_high_risk_pct = """
CREATE OR REPLACE VIEW vw_operational_department_high_risk_pct AS
SELECT department,
ROUND(SUM(risk_score = "High")/ COUNT(risk_score)* 100,2) as percentage_high_risk_visits
FROM visits
GROUP BY department
ORDER BY percentage_high_risk_visits desc;
"""

execute_ddl(create_view_query_high_risk_pct)

df_high_risk_pct = run_query("SELECT * FROM vw_operational_department_high_risk_pct;")
df_high_risk_pct

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

    department  percentage_high_risk_visits
0          ICU                        20.79
1           ER                        20.66
2    Neurology                        20.31
3  Orthopedics                        20.22
4      General                        19.84
5   Cardiology                        18.99

### 4 Determine the average number of visits per patient by city.

In [6]:
create_view_query_visits_per_patient = """
CREATE OR REPLACE VIEW vw_operational_city_avg_visits_per_patient AS
SELECT city,
ROUND(COUNT(visit_id) / COUNT(DISTINCT visits.patient_id), 2) as avg_visits_per_patient
FROM visits JOIN patients
ON visits.patient_id = patients.patient_id
GROUP BY city
ORDER BY avg_visits_per_patient DESC;
"""

execute_ddl(create_view_query_visits_per_patient)

df_visits_per_patient = run_query("SELECT * FROM vw_operational_city_avg_visits_per_patient;")
df_visits_per_patient

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

        city  avg_visits_per_patient
0       Pune                    5.12
1  Hyderabad                    5.06
2  Bangalore                    5.02
3    Chennai                    5.02
4     Mumbai                    5.02
5      Delhi                    4.95

### 5 Identify doctors handling the highest number of High Risk visits.

In [7]:
create_view_query_doctor_high_risk = """
CREATE OR REPLACE VIEW vw_operational_doctor_high_risk_visits AS
SELECT doctor_id,
SUM(risk_score = "High") as high_risk_visit_count
FROM visits
GROUP BY doctor_id
ORDER BY high_risk_visit_count DESC;
"""

execute_ddl(create_view_query_doctor_high_risk)

df_doctor_high_risk = run_query("SELECT * FROM vw_operational_doctor_high_risk_visits;")
df_doctor_high_risk

/Users/narendrafuloria/Desktop/Capstone_IITM/capstone_healthcare_analytics/notebooks/SQL Queries/db_utils.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

     doctor_id  high_risk_visit_count
0          174                   71.0
1          198                   69.0
2          169                   68.0
3          177                   67.0
4          105                   65.0
..         ...                    ...
96         124                   38.0
97         175                   38.0
98         148                   37.0
99         128                   37.0
100        137                   34.0

[101 rows x 2 columns]